### ISSUE TITLE
Update email address the Contact Us form sends to

### ISSUE THREAD

**Issue by steveviens** [awspug/awspug-web#3]
The Contact Us form to so that email messages sent form the form include a subject prefix of [awspug.org] and email is sent to awspug@viens.net

**Comment by ginathegenius** [comment]
@steveviens I was able to update the Subject on the SNS topic to **[awspug.org] Contact Form Inquiry**. Do you have a preference for what the "from" address appears as? They allow this to be changed as well. By default it is **aws-pug Topic**, I changed it to **awspug.org**. Let me know if you want to change it to something else.

**Comment by ginathegenius** [comment]
@steveviens I have updated the CFT stack to send emails to awspug@viens.net. I have sent a test email to make sure its working. Let me know if you get the email!
