### ISSUE TITLE
Link to an auto signup for slack

### ISSUE THREAD

**Issue by cplankey** [awspug/awspug-web#7]

**Comment by steveviens** [comment]
How will this be implemented in the UI?  Do we want to automatically add anyone to the Slack channel or do we want to vet them first (ensure they are already an AWS PUG member)?

**Comment by rocketlobster5** [comment]
Hey Steve, if you check slack, I sent you an example site that lets people into a dev workspace. I setup a security token so the user would need a token from us. It would be a static token, but we could rotate it as needed.
